# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!

target 'WeatherFrogPro' do
  # Pods for WeatherFrogPro
  pod 'Alamofire'
  pod 'ForecastIO'
  pod 'IGListKit'
  pod 'HockeySDK'
  pod 'Sourcery'
  pod 'Swinject'

    target 'WeatherFrogProTests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Nimble'                # a matcher framework
        pod 'Quick'                 # improve tests readability and structure
    end
end

target 'WeatherToday' do
  # Pods for WeatherToday
  pod 'IGListKit'
  pod 'Sourcery'
  pod 'Swinject'

end
